# Generated by Django 6.0.3 on 2026-03-15 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=20)),
                ('mri_image', models.ImageField(upload_to='mri_uploads/')),
                ('predicted_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('all_probabilities', models.JSONField(default=dict)),
                ('gradcam_image', models.TextField(blank=True)),
                ('shap_image', models.TextField(blank=True)),
                ('lime_image', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
