# Generated by Django 6.0.3 on 2026-04-03 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
